# Generated by Django 5.0.6 on 2024-05-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', max_length=10),
        ),
    ]
